# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a8168550497887de13d92fe2811a2f09fe51c92dfdaf98041b6a265fc71571790bc86da0e4bdd53cf78693dcc86ae030a803c40bcba8686ce3afdd54909219

test:
  secret_key_base: 84760ddf5c82a6dd2a98fd4934950d6ce20f20fa5db4043247ad0428528f8211479f8bbec5e639460f486af81f74fd22495a091cfe65908d4daf9fe020bdfe12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
